export const events = [
  {
    title: "React Summit 2026",
    image: "/images/event1.png",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "June 15, 2026",
    time: "09:00 AM",
  },
  {
    title: "Google I/O",
    image: "/images/event2.png",
    slug: "google-io-2026",
    location: "Mountain View, CA",
    date: "May 20, 2026",
    time: "10:00 AM",
  },
  {
    title: "NodeConf 2026",
    image: "/images/event3.png",
    slug: "nodeconf-2026",
    location: "Dublin, Ireland",
    date: "September 8, 2026",
    time: "08:30 AM",
  },
  {
    title: "AWS re:Invent",
    image: "/images/event4.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV",
    date: "November 30, 2026",
    time: "09:00 AM",
  },
  {
    title: "Next.js Global Conference",
    image: "/images/event5.png",
    slug: "nextjs-global-2026",
    location: "San Francisco, CA",
    date: "July 22, 2026",
    time: "10:00 AM",
  },
  {
    title: "TechCrunch Disrupt",
    image: "/images/event6.png",
    slug: "tc-disrupt-2026",
    location: "New York, NY",
    date: "October 5, 2026",
    time: "08:00 AM",
  },
];
